version: "3"
services:
  app:
    build: .
    image: fahadkamran2001/ca4-server:latest
    container_name: ca4-server
    links:
      - db
    ports:
      - "5000:5000"
    environment: mysql://root:root@db:3300/users
    depends_on:
      - db
  db:
    image: fahadkamran2001/ca4-db:latest
    container_name: ca4-db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
networks:
  default:
    external:
      name: flaskSqlNetwork
