version: "3"
services:
  db:
    image: fahadkamran2001/ca4-db:latest
    container_name: ca4-db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiger123
      MYSQL_DATABASE: users
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  app:
    image: fahadkamran2001/ca4-server:latest
    container_name: ca4-server
    links:
      - db
    ports:
      - "5000:5000"
    environment: mysql://root:tiger123@db:3300/users
    depends_on:
      - db
networks:
  default:
    external:
      name: flaskSqlNetwork
